export const THEME = {
  colors: {
    bg: {
      warmIvory: '#F7F4ED',
      warmWhite: '#FCFBF8',
      softStone: '#EBE7DF',
      deepGreen: '#173C2B',
      botanicalGreen: '#2E6B4A',
      arogyaMaroon: '#6A1423',
      deepBurgundy: '#3D0B15',
      obsidianDark: '#0F0F11',
      charcoalDark: '#171717',
    },
    brand: {
      primary: '#6A1423',
      primaryHover: '#8b1528',
      darkMaroon: '#3D0B15',
      accentGold: '#C7A33A',
      accentGoldLight: '#F3E5AB',
      botanicalGreen: '#2E6B4A',
      deepGreen: '#173C2B',
    },
    text: {
      charcoal: '#171717',
      darkSecondary: '#4A4A4A',
      darkMuted: '#6B6B6B',
      lightPrimary: '#FCFBF8',
      lightSecondary: '#EBE7DF',
      lightMuted: '#9E9EA7',
      gold: '#C7A33A',
    },
    border: {
      subtleLight: '#EBE7DF',
      mediumLight: '#DCD6C8',
      subtleDark: 'rgba(255, 255, 255, 0.1)',
      brandMaroon: 'rgba(106, 20, 35, 0.3)',
    },
    status: {
      success: '#2E6B4A',
      warning: '#C7A33A',
      error: '#CF1322',
      info: '#1890FF',
    },
  },
  fonts: {
    serifDisplay: "'Cinzel', Georgia, serif",
    sansBody: "'Inter', system-ui, sans-serif",
    sansDisplay: "'Outfit', sans-serif",
  },
  radii: {
    none: '0px',
    sm: '6px',
    md: '12px',
    lg: '20px',
    xl: '28px',
    full: '9999px',
  },
  maxWidths: {
    container: '1280px',
    narrowContainer: '1024px',
    readingContainer: '768px',
  },
} as const;
